// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef test1_h
#define test1_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>

class SimpleUI {
public:
  SimpleUI();
};
#endif
